.gitignore, .travis.yml, ci_build.sh, configure.ac, project.xml, src/fty-sensor-gpio.service.in, src/libfty_sensor_gpio.pc.in
Regenerate with current zproject; update reference to fty_proto, czmq, malamute according to fty-example template
=> Bump project

README.md, src/fty_sensor_gpio_alerts.cc, src/fty_sensor_gpio_assets.cc, src/fty_sensor_gpio_server.cc
=> Problem: need to update subtype to sensorgpio

src/42ity-gpio-permissions
Solution: Set the execution flags
=> Problem: udev script must be executable

install.xml, src/fty-sensor-gpio.conf
Solution: Add a systemd-tmpfiles
=> Problem: Need RW access to the data dir

src/fty_sensor_gpio_server.cc
=> Problem: REST API needs us to wrap GPIO_MANIFEST message in zuuid.

README.md, include/fty_sensor_gpio.h, include/fty_sensor_gpio_assets.h, include/libgpio.h, src/fty-sensor-gpio.cfg.in, src/fty_sensor_gpio.cc, src/fty_sensor_gpio_alerts.cc, src/fty_sensor_gpio_assets.cc, src/fty_sensor_gpio_server.cc, src/libgpio.cc, src/selftest-ro/data/DCS001.tpl, src/selftest-ro/data/GPOTEST.tpl, src/selftest-ro/data/M12.tpl, src/selftest-ro/data/VIB001.tpl, src/selftest-ro/data/WLD012.tpl, src/selftest-ro/data/XCELW.tpl
Problem: XCELW normal-state is incomplete
Solution: Complete it
Problem: 2 sec poll_interval is too much
Solution: Use 10 sec poll_interval
Problem: Template need a power-source field
Solution: Add it and update documentation
=> Problem: Various problems

README.md, include/fty_sensor_gpio_assets.h, src/fty_sensor_gpio.cc, src/fty_sensor_gpio_assets.cc, src/fty_sensor_gpio_server.cc
Solution: Use gpo_powersource and update code and doc
=> Problem: GPI powered by GPO should use ext. attribute

README.md, src/fty_sensor_gpio_assets.cc
Problem: Extraneous trace remaining
Solution: Remove it
Problem: Example CSV needs complementary information
Solution: Add some notes and complete the example
=> Problem: various minor improvements needed

src/fty_sensor_gpio_server.cc, src/libgpio.cc
Solution: Improve debug traces and errors reporting
=> Problem: Error msg can be redundant or not applicable

src/fty-sensor-gpio.cfg.in
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
=> Problem : GPO pins have +20 offset (not +15)

src/libgpio.cc
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
=> Problem: GPO9-10 offset is different from GPO1-3

src/fty-sensor-gpio.service.in
=> Problem: 'gpio' group missing

src/fty_sensor_gpio_alerts.cc
=> Problem: alert message is sent with incorrect subject

src/fty_sensor_gpio_assets.cc, src/fty_sensor_gpio_server.cc
Solution: added sensors identification in aux message part
=> Problem: sensors are identified only by port, using this with other sensor sources will cause overlap

src/fty_sensor_gpio_assets.cc
Solution: Added support for zuuid in some messages
=> Problem: Missing zuuid in mailbox messages

src/libgpio.cc
=> Problem: libgpio_export/unexport still adds base address.

src/fty_sensor_gpio_assets.cc
=> Problem: we have new asset subtype gpo

README.md, src/fty_sensor_gpio_server.cc
Solution: Test and document it. Also, fix the formatting of README because marked cannot render a proper HTML out of it.
=> Problem: GPOSTATE command is not tested or documented.

src/fty_sensor_gpio_assets.cc
=> Problem: we need to update initial request

src/fty_sensor_gpio_assets.cc, src/fty_sensor_gpio_server.cc
Solution: Update it; remove dead code left over from previous PR.
=> Problem: Tests use old subtype for GPO.

src/fty_sensor_gpio.cc, src/fty_sensor_gpio_assets.cc
Solution: replaced by asset_detail
=> Problem: we would like to remove republish MB command

src/fty_sensor_gpio_server.cc
Solution: Store the new default state and if the GPO is not used for alerts, switch it into the new state.
=> Problem: We need to act on change of default state.

src/fty_sensor_gpio_assets.cc
Solution: Filter out inactive assets and add tests
=> Problem: Inactive assets are monitored

src/fty_sensor_gpio_assets.cc, src/fty_sensor_gpio_server.cc
Solution: Use the verbose conditioned function
=> Problem: Agent is too verbose when not needed

README.md, include/fty_sensor_gpio.h, include/libgpio.h, src/fty-sensor-gpio.service.in, src/fty_sensor_gpio.cc, src/fty_sensor_gpio_assets.cc, src/fty_sensor_gpio_server.cc, src/libgpio.cc
Solution: Implement it, with more tests
=> Problem: Need to handle HW_CAP request

src/selftest-ro/data/M12.tpl
=> Problem: Smoke detector normal state is also wrong

src/selftest-ro/data/M12.tpl, src/selftest-ro/data/VIB001.tpl, src/selftest-ro/data/XCELW.tpl
Solution: Backport from master
=> Problem: Some sensors normal state are wrong

src/fty_sensor_gpio_server.cc
=> Problem: Error messages are OK/ERROR/<error message>, but fty-rest expects ERROR/<error_message>

install.xml
=> Problem: Template for Zettler MZX-e are not shipped
